#!/bin/bash

STDPATH="~/Documents/latexstd/"
SERVERSCRIPTPATH="~/Documents/bash/latexal/latexal_s"

function updateServer {
	ssh $1 "mkdir -p ~/latex"
	scp $SERVERSCRIPTPATH $1:~/latex/
	ssh $1 "chmod u+x ~/latex/latexal_s"
	echo " * server script updated"

	scp -r $STDPATH $1:~/latex/ 1> /dev/null
	echo " * server standard includes updated"
	echo ""
}

function buildC {
	set -e
	# Handle func inputs ---------------------------------------------------------
	name=""
	dir=""
	[ $2 = "." ] &&
		{ name=${PWD##*/} && dir="${PWD}";       } ||
		{ name=$2         && dir="${PWD}/$name"; }

	# test if directory exists, if not: exit
	[ -d $dir ] || { echo "Directory $name doesn't exist" && return 1; }

	# Init -----------------------------------------------------------------------
	# skapar directory för projekt och kopierar över hela mappen
	ssh $1 "mkdir ~/latex/$name" &> /dev/null || :
	scp -r $dir $1:~/latex/ 1> /dev/null

	echo "project folder copied: $1:~/latex/$name"

	# Run server -----------------------------------------------------------------
	# ssh till hostnamn

	# run serverside script
	ssh $1 "~/latex/latexal_s $name"

	# Fetching -------------------------------------------------------------------
	# collect pdf from server
	scp $1:~/latex/$name/main.pdf $dir &> /dev/null || :

	success=0
	[ -f "$dir/main.pdf" ] && success=1

	# om pdf inte finns, hämta log
	if [ $success -eq 1 ]; then
		echo "Build succeded. $name.pdf fetched!"
	else
		echo "Failed build for $name.pdf. Fetching log..."
		scp $1:~/latex/$name/main.log $dir 1> /dev/null
	fi

	# Cleanup --------------------------------------------------------------------
	# output status
	if [ $success -eq 1 ]; then
		mv $dir/main.pdf $dir/$name.pdf
		WORDS=$(pdftotext $dir/$name.pdf - | egrep -e '\w\w\w+' | wc -w)
		FILESIZE=$(ls -lah $dir/$name.pdf | awk '{ print $5}')
		VICOUNTER=$(pdftotext $dir/$name.pdf - | grep -i 'vi ' | wc -l)
		echo "Build took $SECONDS seconds. [${FILESIZE}B, ${WORDS} words, ${VICOUNTER} VI]"
	fi

	# ta bort kopia på servern
	ssh $1 "rm -r ~/latex/$name"

}

function helpC {
	echo "Usage: latexal <command> <parameters>"
	echo "   build <hostname> <directory>"
	echo "          Copies project directory to host and compiles it."
	echo "		Project directory assumed to have a main.tex file."
	echo "   update <hostname>"
	echo "          Updates serverscript and std includes."
}

# MAIN PROGRAM
echo "LaTeXal 0.15"
echo " - github.com/ollelogdahl"
echo ""

cmd=$1
# handle commands
srv=$2
dir=${3%/}
case "$cmd" in
	build)  buildC $srv $dir ;;			# runs build command on server
	update) updateServer $srv ;;		# update server script and std/
	help)   helpC ;;
	*) { echo "Invalid Command!" && helpC; } ;;
esac
