#!/bin/bash

STDPATH="D/LaTeX/std/"
TEMPLATEPATH="D/LaTeX/templates"

function updateServer {
	scp ~/scripts/latexal_s $1:~/latex/ 1> /dev/null
	ssh $1 "chmod u+x ~/latex/latexal_s"
	echo " * server script updated"

	scp -r ~/$STDPATH $1:~/latex/ 1> /dev/null
	echo " * server standard includes updated"
	echo ""
}

function buildC {
	# Handle func inputs ---------------------------------------------------------
	name=""
	dir=""
	[ $2 = "." ] &&
		{ name=${PWD##*/} && dir="${PWD}";       } ||
		{ name=$2         && dir="${PWD}/$name"; }

	# test if directory exists, if not: exit
	[ -d $dir ] || { echo "Directory $name doesn't exist" && return 1; }

	# Init -----------------------------------------------------------------------
	# skapar directory för projekt och kopierar över hela mappen
	ssh $1 "mkdir ~/latex/$name" &> /dev/null || :
	scp -r $dir $1:~/latex/ 1> /dev/null

	echo "project folder copied: $1:~/latex/$name"

	# Run server -----------------------------------------------------------------
	# ssh till hostnamn

	# run serverside script
	now=${date +"%T"}
	echo "[ $now Latexal started]"
	ssh $1 "~/latex/latexal_s $name"

	# Fetching -------------------------------------------------------------------
	# collect pdf from server
	scp $1:~/latex/$name/main.pdf $dir > /dev/null 2>&1 || :

	success=0
	[ -f "$dir/main.pdf" ] && success=1

	# om pdf inte finns, hämta log
	if [ $success -eq 1 ]; then
		echo "Build succeded. $name.pdf fetched!"
	else
		echo "Failed build for $name.pdf. Fetching log..."
		scp $1:~/latex/$name/main.log . 1> /dev/null
	fi

	# Cleanup --------------------------------------------------------------------
	# ta bort kopia på servern
	ssh $1 "rm -r ~/latex/$name"

	# output status
	if [ $success -eq 1 ]; then
		mv $dir/main.pdf $dir/$name.pdf

		FILESIZE=$(ls -lah $dir/$name.pdf | awk '{ print $5}')
		echo "Build took $SECONDS seconds. [${FILESIZE}B]"
	fi
}

function newC {
	template=$1
	filename=$2

	# find template in TEMPLATEPATH
	tpath="${TEMPLATEPATH}/${template}.tex"
	if test -f ~/"$tpath"; then
		mkdir $filename
		cp ~/$tpath $filename/main.tex
		echo "Template copied!"
	else
		echo "$tpath"
		echo "Template $template doesn't exist!"
	fi
}

function helpC {
	echo "Usage: latexal <command> <parameters>"
	echo "   build <hostname> <directory>"
	echo "          Copies project directory to host and compiles it."
	echo "   update <hostname>"
	echo "          Updates serverscript and std includes."
	echo "   new <template> <name>"
	echo "          Creates a new project directory, copying an existing template."
}

# MAIN PROGRAM
echo "LaTeXal 0.14"
echo " - github.com/ollelogdahl"
echo ""

set -e

cmd=$1
# handle commands
srv=$2
dir=${3%/}
case "$cmd" in
	build)  buildC $srv $dir ;;			# runs build command on server
	update) updateServer $srv ;;		# update server script and std/
	new)    newC $2 $3 ;;						# creates a new .tex file from a template
	help)   helpC ;;
	*) { echo "Invalid Command!" && helpC; } ;;
esac
